# Generated by Django 3.0.6 on 2020-12-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.ManyToManyField(to='vison.Type'),
        ),
        migrations.AlterField(
            model_name='vcsentence',
            name='vocab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vison.VcVocab'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='antonym',
            field=models.ManyToManyField(blank=True, related_name='vison_vocab_related_antonym', to='vison.Vocab'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='category',
            field=models.ManyToManyField(to='vison.Tag'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='seealso',
            field=models.ManyToManyField(blank=True, related_name='vison_vocab_related_see_also', to='vison.Vocab'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='source',
            field=models.ManyToManyField(to='vison.Source'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='synonym',
            field=models.ManyToManyField(blank=True, related_name='vison_vocab_related_synonym', to='vison.Vocab'),
        ),
    ]
