# Generated by Django 2.0 on 2018-05-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VcSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VcVocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('meaning', models.CharField(max_length=450)),
                ('short_def', models.TextField()),
                ('long_def', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('meaning', models.CharField(max_length=250)),
                ('sentences', models.TextField()),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('antonym', models.ManyToManyField(blank=True, related_name='gre_vocab_related_antonym', to='gre.Vocab')),
                ('category', models.ManyToManyField(to='gre.Tag')),
                ('seealso', models.ManyToManyField(blank=True, related_name='gre_vocab_related_see_also', to='gre.Vocab')),
                ('source', models.ManyToManyField(to='gre.Source')),
                ('synonym', models.ManyToManyField(blank=True, related_name='gre_vocab_related_synonym', to='gre.Vocab')),
            ],
        ),
        migrations.AddField(
            model_name='vcsentence',
            name='vocab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gre.VcVocab'),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.ManyToManyField(to='gre.Type'),
        ),
    ]
