# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('meaning', models.CharField(max_length=250)),
                ('sentences', models.TextField()),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('antonym', models.ManyToManyField(blank=True, related_name='gre_vocab_related_antonym', to='gre.Vocab')),
                ('category', models.ManyToManyField(to='gre.Tag')),
                ('seealso', models.ManyToManyField(blank=True, related_name='gre_vocab_related_see_also', to='gre.Vocab')),
                ('synonym', models.ManyToManyField(blank=True, related_name='gre_vocab_related_synonym', to='gre.Vocab')),
            ],
        ),
    ]
