# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='source',
            field=models.CharField(default='unknown', max_length=40),
            preserve_default=False,
        ),
    ]
