# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0002_vocab_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vocab',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.ManyToManyField(to='gre.Type'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='source',
            field=models.ManyToManyField(to='gre.Source'),
        ),
    ]
