# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gre', '0003_auto_20160328_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VcVocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('meaning', models.CharField(max_length=450)),
                ('short_def', models.TextField()),
                ('long_def', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vcsentence',
            name='vocab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gre.VcVocab'),
        ),
    ]
